ALTER TABLE users ADD COLUMN mode TEXT NOT NULL DEFAULT 'newbie';
ALTER TABLE users ADD COLUMN progress_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN full_access INTEGER NOT NULL DEFAULT 0;
